### ISSUE TITLE
Pagina "quienes somos"

### ISSUE THREAD

**Issue by LeandroZipitria** [UnaImagen/UnaImagen#16]
Armé un prototipo de página "quienes somos" (quienes-somos.Rmd).
Les pido que agreguen su información. Tengo algunos problemas que no puedo resolver.

1) como insertar una imagen. Debe ser en una carpeta imagenes, que pongamos en el repositorio con todas las imagenes (incluido el favicom).
2) si se puede armar una página en vez de un post.

**Comment by daczarne** [comment]
Ya cree la página con acceso desde el sidemenu y moví todo al branch quienes-somos para poder trabajar en el tema tranquilos y sin romper la página

**Comment by daczarne** [comment]
Ambos ítems tratados en commit fa73295675b7444d5b8c236a3fb0b87a466ca1b7

Las imágenes se agregan en static/img/NombreApellido.jpg

Se configuró el Rmd como página en lugar de post

**Comment by daczarne** [comment]
merged to master on 0a15bc744eacb58a005ac9c72be53424a85213f4
