### ISSUE TITLE
widget-lazy-load

### ISSUE THREAD

**Issue by daczarne** [UnaImagen/UnaImagen#17]
Actualmente tenemos un problema que por lo que estuve leyendo creo que podemos solucionarlo bastante fácilmente. Los mapas son muuuuuy pesados (ver primer imagen):

![image](https://user-images.githubusercontent.com/16988051/81466662-b2979300-91a9-11ea-8309-56e53d5a7d47.png)

Esto impacta de dos posibles formas:

- Si el mapa está incrustado en el post, entonces la carga de la página es super lenta porque implica cargar toda la página (aparentemente). Ver commit 43a938f. Pasé el widget del mapa a una página propia la cual es cargada solo cuando el usuario entra al post específico.  

- Si el mapa es cargado con la estrategía indicada arriba, entonces la carga de la página parecería estarse haciendo más rápido, pero la carga del post no, dado que cuando el usuario entra al post se tienen que cargar los 32MBs del mapa completo.

**Propuesta:** centrar el mapa en, por ejemplo, Montevideo (de esto es que necesito que te encargues @LeandroZipitria), y utilizar una carga con lazy load (yo me encargo de esta parte). Ver segunda imagen:

![image](https://user-images.githubusercontent.com/16988051/81466737-3d788d80-91aa-11ea-924d-0941deb0c613.png)

De esta forma la página solo debería cargar la parte de la información necesaria para generar esa parte del widget, y luego ir cargando las demás partes a medida que el usuario empieza a navegar por el mapa.

Si esto funciona, en una segunda iteración podemos explorar la opción de que la ciudad que se carga por default sea la ciudad donde está el usuario cuando ingresa (asumiendo que sea en Uruguay, y sino que se cargue Mvdeo por default).

**Comment by daczarne** [comment]
Para que el mapa se cargue en la ciudad desde donde el usuario está ingresando usamos

`leaflet() %>%
    addTiles() %>%
    onRender("
      function(el, x) {
        // Navigate the map to the user's location
        this.locate({setView: true});
     }
  ")`

**Comment by LeandroZipitria** [comment]
arreglado en commits 136b44a0ab92a82bd1898818c191502bd7f5bb94, 837e7b05e317e8e99cecb4b84351a3b660492dbd y
d40718b63d3e50f20981b473896deeac82c86905
