### ISSUE TITLE
Cambiar escala del mapa de ingresos?

### ISSUE THREAD

**Issue by lucila-bonilla** [UnaImagen/UnaImagen#18]
Los departamentos aparecen todos del mismo color porque tienen ingresos "similares" y luego en Montevideo si se ven colores diferentes (zona costera). 
Se puede alterar esto? Quizás hacer dos escalas, una departamental y luego una en otros colores para barrios de Montevideo?

**Comment by LeandroZipitria** [comment]
Respondo por aca. Use la paleta de colores "Blues" y que lo tome en el domain de valores de ingresos en dolares. Supongo que es continuo, y los contrastes son porque hay pocas diferencias de ingresos promedios entre departamentos, pero brutales dentro de montevideo.
