### ISSUE TITLE
Revisar base y agregar resultados

### ISSUE THREAD

**Issue by daczarne** [UnaImagen/UnaImagen#4]
Hay varios formatos distintos para los pdfs con la información de cada circuito. Ya armé el parseo del de Artigas. Con algunas modificaciones se podrían hacer el resto, pero sería óptimo conseguirlos en csv

**Comment by LeandroZipitria** [comment]
Este proyecto hay que abandonarlo. Muy complicado y ya pasó el momento.

**Comment by daczarne** [comment]
Concuerdo. En todo caso los datos quedan y después vemos de re abrirlo
