### ISSUE TITLE
Escala mapa juntos o separados

### ISSUE THREAD

**Issue by daczarne** [UnaImagen/UnaImagen#8]
Necesitamos modificar la escala del mapa. La actual genera que practicamente todo Mvdeo se vea igual. El primer rango va entre 0 y 1, mientras que el último va entre 11k y 73k. Estoy mirando los .R del Censo2011 pero están un poco sucios. ¿De dónde sale personas.rds? Tenemos el .R que lo genera en el repo o quedó en algún otro lado?

**Comment by LeandroZipitria** [comment]
Done

**Comment by daczarne** [comment]
escala corregida en commit c326f5e3b5b90db6d649c30d83f1f6422e66397d. Se cambió la distribución de percentiles a una no uniforme. Adicionalmente, en commit e544439ff89e439851314bc4243bb4919d200360 se ajusta el formato de la leyenda
